//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STRM_M.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cord_image
    {
        public int ID { get; set; }
        public Nullable<int> STORAGE_ID { get; set; }
        public string CORD_X { get; set; }
        public string CORD_Y { get; set; }
        public string ICON { get; set; }
        public string MODAL { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
