//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STRM_M.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_storage_auto_trackin
    {
        public int ID { get; set; }
        public Nullable<int> LOC_ID { get; set; }
        public string STORAGE_PROCESS { get; set; }
        public string TYPE_FORMAT_ALIAS { get; set; }
        public string TYPE_RECEPIT { get; set; }
        public string COLOR { get; set; }
    }
}
