//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STRM_M.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_storage_information
    {
        public int LOC_ID { get; set; }
        public Nullable<int> BIZ_ID { get; set; }
        public Nullable<int> STORAGE_TYPE_ID { get; set; }
        public string STORAGE_NO { get; set; }
        public string STORAGE_ORDER_NO { get; set; }
        public Nullable<int> STORAGE_CONDITION_ID { get; set; }
        public string STORAGE_PROCESS { get; set; }
        public string TYPE_FORMAT_ALIAS { get; set; }
        public Nullable<int> STORAGE_MAX { get; set; }
        public Nullable<int> STORAGE_TOTAL { get; set; }
        public Nullable<int> STORAGE_STATUS { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
