//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STRM_M.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_temp_maual_data
    {
        public int ID { get; set; }
        public string LOT_NO { get; set; }
        public string PART_CODE { get; set; }
        public string QUANTITY { get; set; }
        public Nullable<int> LOC_ID { get; set; }
        public string MAN_NAME { get; set; }
        public string OPE_NAME { get; set; }
        public string HOLD_DESC { get; set; }
    }
}
