//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STRM_M.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_transaction
    {
        public int TRAN_ID { get; set; }
        public string LOT_NO { get; set; }
        public string PART_CODE { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<int> TYPE_SYSTEM_ID { get; set; }
        public Nullable<int> TYPE_TRAN_ID { get; set; }
        public Nullable<int> LOC_ID { get; set; }
        public string REGISTER_BY { get; set; }
        public Nullable<System.DateTime> REGISTER_DATE { get; set; }
        public string TAKE_OUT_BY { get; set; }
        public Nullable<System.DateTime> TAKE_OUT_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string FLAG_CONFIRM { get; set; }
    }
}
