//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STRM_M.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_type_storage_format
    {
        public string TYPE_FORMAT_ALIAS { get; set; }
        public string TYPE_FORMAT_NAME { get; set; }
    }
}
